#!/bin/sh

for i in 0 `seq 1 12 ` ; do scp do180_ocp4.0_hotfix w$i:  & done

for i in 0 `seq 1 12 ` ; do ssh w$i bash do180_ocp4.0_hotfix   & done

# for i in master0 worker{0,1} ; do ( rht-vmctl  stop  $i ; rht-vmctl  start  $i ) & done

rht-each --spawn  '"for i in master0 worker{0,1} ; do ( rht-vmctl  stop  \$i ; rht-vmctl  start  \$i ) & done"'

for i in 0 `seq 1 12 ` ; do echo =======> w$i : ; ssh w$i oc login --insecure-skip-tls-verify=true -u kubeadmin -p $(cat .kubeadmin) https://cluster-api.lab.example.com:6443 | grep default ; done





oc login --insecure-skip-tls-verify=true -u kubeadmin -p $(cat .kubeadmin) https://cluster-api.lab.example.com:6443
oc new-project test 
oc new-app registry.lab.example.com/httpd:2.4 --insecure-registry 
oc get pod -w 

oc new-app --docker-image=registry.lab.example.com/rhscl/mysql-57-rhel7:latest --name=mysql-openshift -e MYSQL_USER=user1 -e MYSQL_PASSWORD=mypa55 -e MYSQL_DATABASE=testdb -e MYSQL_ROOT_PASSWORD=r00tpa55 --insecure-registry=true


oc port-forward mysql-openshift-1-qs7cm 3306:3306 &

echo "show databases;" | mysql -uuser1 -pmypa55 --protocol tcp -h localhost

oc delete project test


oc new-project route

oc new-app php:5.6~http://services.lab.example.com/php-helloworld 

oc get pod -w

oc logs -f bc/php-helloworld

oc logs -f dc/php-helloworld

oc describe svc/php-helloworld

oc expose svc/php-helloworld



curl php-helloworld-route.apps.cluster.lab.example.com

oc expose svc/php-helloworld --name=xyz 


curl xyz-route.apps.cluster.lab.example.com

oc delete project route

lab openshift-s2i start 

cd ~/DO180/labs/openshift-s2i

tree -C s2i-php-container

oc new-project s2i

oc new-app -i php:5.6 --name=php-helloworld http://services.lab.example.com/php-helloworld 

oc get pod -w

oc logs --all-containers -f php-helloworld-1-build 

oc expose svc/php-helloworld --name helloworld

curl helloworld-s2i.apps.cluster.lab.example.com


git clone http://services.lab.example.com/php-helloworld 

cd php-helloworld

cat >index.php <<EOF 
<?php
print "Hello, World! php version is " . PHP_VERSION . "\n";
print "A change is coming!\n";
?>
EOF

git add index.php 
git commit -m 'Changed index page contents.'
git push origin master
oc start-build php-helloworld
oc logs --all-containers -f php-helloworld-2-build 
curl helloworld-s2i.apps.cluster.lab.example.com

lab openshift-s2i finish


lab openshift-webconsole start

firefox  https://console-openshift-console.apps.cluster.lab.example.com

