#!/bin/sh

for i in 0 `seq 1 12 ` ; do scp do180_ocp4.0 w$i:  & done

for i in 0 `seq 1 12 ` ; do ssh w$i bash do180_ocp4.0 & done

# for i in master0 worker{0,1} ; do ( rht-vmctl  stop  $i ; rht-vmctl  start  $i ) & done

rht-each --spawn  '"for i in master0 worker{0,1} ; do ( rht-vmctl  stop  \$i ; rht-vmctl  start  \$i ) & done"'

for i in 0 `seq 1 12 ` ; do echo =======> w$i : ; ssh w$i oc login --insecure-skip-tls-verify=true -u kubeadmin -p $(cat .kubeadmin) https://cluster-api.lab.example.com:6443 | grep default ; done
